feat: Allow user scope to view old events
Tietokilta/ilmomasiina pull request #153
Opened 2024-10-24 13:14 UTC by joonatanaatos

2024-10-27 21:05 UTC, PurkkaKoodari requested changes

2024-10-27 21:05 UTC, PurkkaKoodari commented on packages/ilmomasiina-backend/src/models/event.ts
> -              },
I think we'll still want a hard limit for regular users

2024-10-27 21:05 UTC, PurkkaKoodari commented on packages/ilmomasiina-backend/src/routes/events/getEventsList.ts
> +  async get(options: { category?: string; since?: Date }) {
This won't work with the current caching system, which compares the function argument with `Object.is` (using a `Map`)

2024-10-27 21:05 UTC, PurkkaKoodari commented on packages/ilmomasiina-backend/src/routes/events/getEventsList.ts
> +        [Op.gt]: since,
`Op.gte` would probably be more exact

2024-10-27 21:05 UTC, PurkkaKoodari commented on packages/ilmomasiina-models/src/schema/eventList/index.ts
> +  ),
`Type.Date` is a [typebox extension](https://github.com/sinclairzx81/typebox?tab=readme-ov-file#javascript-types), it doesn't actually parse the dates. You'll need to use `Type.String` with [`format: "date-time"`](https://json-schema.org/draft/2020-12/json-schema-validation#section-7.3.1-4.2) and parse yourself (like we do in e.g. [`updateEvent`](https://github.com/Tietokilta/ilmomasiina/blob/cf0a1fd003f235b1ed0128c38dd0de18e7f03940/packages/ilmomasiina-backend/src/routes/admin/events/updateEvent.ts#L83-L86))

2024-11-21 20:01 UTC, kahlstrm approved these changes
Looks good 👌

2024-11-21 20:01 UTC, merged